# Generated by Django 6.0.3 on 2026-03-14 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Varlık Adı')),
                ('asset_type', models.CharField(choices=[('crypto', 'Kripto Para'), ('stock', 'Hisse Senedi'), ('gold', 'Altın'), ('manual', 'Manuel Değer')], max_length=20, verbose_name='Tip')),
                ('symbol', models.CharField(blank=True, max_length=50, verbose_name='Sembol (BTC, AAPL vb.)')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Miktar')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Alış Fiyatı')),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Güncel Fiyat')),
                ('currency', models.CharField(choices=[('USD', 'Dolar'), ('TRY', 'Türk Lirası'), ('EUR', 'Euro')], default='USD', max_length=5, verbose_name='Para Birimi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Varlık',
                'verbose_name_plural': 'Varlıklar',
                'ordering': ['asset_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Satın Al'), ('sell', 'Sat'), ('add', 'Miktar Ekle')], max_length=10, verbose_name='İşlem Tipi')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Miktar')),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='İşlem Fiyatı')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tracker.asset')),
            ],
            options={
                'verbose_name': 'İşlem',
                'verbose_name_plural': 'İşlemler',
                'ordering': ['-date'],
            },
        ),
    ]
